import { StyleSheet } from "react-native";
export default sty = StyleSheet.create({
    img:{
        width:"100%",
        height:"100%",
    },
    setting:{
        width:"100%",
        height:50,
        // backgroundColor:"red",
        justifyContent:"center",
    },
    settingtext:{
        fontSize:20,
        color:"white",
        marginLeft:10,
    },
    main:{
        width:"100%",
        height:80,
        // backgroundColor:"grey",
        justifyContent:"center"
    },
    mainin:{
        width:"30%",
        height:30,
        // backgroundColor:"rgba(52, 52, 52, 0.8)",
        marginLeft:10,
        borderRadius:8,
        display:"flex",
        flexDirection:"row"
    },
    temp:{
        color:"white",
        marginLeft:10,
    },
    mainleft:{
        width:"50%",
        height:30,
        backgroundColor:"orange",
        borderTopLeftRadius:8,
        borderBottomLeftRadius:8,
        justifyContent:"center",
        alignItems:"center"
    },
    mainright:{
        width:"50%",
        height:30,
        backgroundColor:"pink",
        borderTopRightRadius:8,
        borderBottomRightRadius:8,
        justifyContent:"center",
        alignItems:"center"
    },
    mainin3:{
        width:"40%",
        height:30,
        backgroundColor:"rgba(52, 52, 52, 0.8)",
        marginLeft:10,
        borderRadius:8,
        display:"flex",
        flexDirection:"row"
    },
    mainleft3:{
        width:"35%",
        height:30,
        backgroundColor:"orange",
        borderTopLeftRadius:8,
        borderBottomLeftRadius:8,
        justifyContent:"center",
        alignItems:"center"
    },
    mainright3:{
        width:"35%",
        height:30,
        backgroundColor:"yellow",
        justifyContent:"center",
        alignItems:"center",
        borderStyle:"solid",
        borderWidth:2,
        borderTopColor:"yellow",
        borderLeftColor:"yellow",
        borderBottomColor:"yellow",
        borderRightColor:"yellow"
    },
    mainin3:{
        width:"60%",
        height:30,
        // backgroundColor:"rgba(52, 52, 52, 0.8)",
        marginLeft:10,
        borderRadius:8,
        display:"flex",
        flexDirection:"row"
    },
    mainend:{
        width:"35%",
        height:30,
        backgroundColor:"pink",
        borderTopRightRadius:8,
        borderBottomRightRadius:8,
        justifyContent:"center",
        alignItems:"center"
    }
})